### ISSUE TITLE
Use ES6 features

### ISSUE THREAD

**Issue by joefitter** [UKHomeOffice/hof-controllers#27]
HOF-Controllers should be refactored to utilise ES6 supported in node 4.x. In particular:
- Block scoping `let`, `const` and scoped `function` declarations
- Classes
- Object literal extensions
- Template strings
- Arrow functions

**Comment by easternbloc** [comment]
👍 will require a major version but this is a good thing.

**Comment by joefitter** [comment]
Agree - we call controllers without the new keyword in form applications which throws an error, this will need to be fixed across the board in order to utilise classes
