### ISSUE TITLE
Editing a forked journey is still broken?

### ISSUE THREAD

**Issue by daniel-ac-martin** [UKHomeOffice/hof-controllers#33]
I believe that editing a forked journey is still broken in some situations. Though I don't have much time to investigate this properly at the moment.

Specifically, I believe that if one goes through a form down through a fork to a confirm page. Then goes back and edits the stop with the forking point so that they _should_ be sent down the default path (which they did not complete) they will instead be sent straight back to the confirm page.

This is because whilst we check all of the forks to ensure we have been down them prior to sending them to the confirm page. We do _not_ do this for the default journey.

In a way this highlights the ugliness of the "forks" property. Perhaps in the future we should abandon it in favour of expanding the concept of the "next" property itself. (It could even be a function though of course people will do crazy things with that. - Do we care?)

**Comment by JoeChapman** [comment]
@daniel-ac-martin why do you think it is ugly?

**Comment by joefitter** [comment]
@easternbloc https://github.com/UKHomeOffice/hof-controllers/commit/cb47acd758962ee6ab82636399f944f044f983f8#diff-fef1d324efc1b19210d17ad182a5a239R42 This line always returns false on the first pass through the step

**Comment by daniel-ac-martin** [comment]
@JoeChapman Just because it opens us up to making mistakes like this. There's really no difference between a "next step" that comes from the next property and one that comes from a fork. They need to be processed the same.

I also feel that it implies that one is secondary to the other. If we talk about a fork in a road we don't necessarily ask which is the primary path to take and which is the secondary.

@joefitter Don't you mean that it always returns true? (There is a ! in there.) That is exactly what we want to happen on the first pass. The code you commented on has now been replaced by mine, but mine has an equivalent line. (It's commented though so hopefully will make more sense. - If not, give me a shout and I will do my best to explain it.)

**Comment by daniel-ac-martin** [comment]
(Once any questions have been answered, we should close this issue as the PR has now been merged.)

**Comment by joefitter** [comment]
@daniel-ac-martin I misworded my comment, sorry! What I mean is, if you complete a form going down one fork, then go back to the step where the fork is located, change something (that doesn't affect the fork), clicking continue takes you to the 'next' page, not the fork target as would have been expected. This is because of the line I highlighted as the fork condition is only respected if the fork page isn't already stored in session steps, so second time around, it ignores the fork

**Comment by joefitter** [comment]
Just seen the refactor of the getNextStep method, ignore, I'll try that 😄

**Comment by daniel-ac-martin** [comment]
@joefitter In the old version there was some code later on that would take you back to the confirm page rather than down the "next" path. So I think that aspect of the code was fine. But anyway it's gone now, probably replaced by a new and interesting set of bugs.

**Comment by joefitter** [comment]
probably! One I have just noticed is this line - https://github.com/UKHomeOffice/hof-controllers/blob/master/lib/base-controller.js#L33 - the step passed in has the `basePath` prepended so is never found in the session stored steps list

**Comment by joefitter** [comment]
in GRO anyway. Just trying to fix our newly failing acceptance tests since the change

**Comment by JoeChapman** [comment]
UKHomeOffice/hof anyone know what the status of this is?

**Comment by joefitter** [comment]
Forking still isn't working correctly IMO as if you complete a form, then go back to a fork condition and amend it, the now invalid steps remain in session model, along with any fields they contain - my PR - https://github.com/UKHomeOffice/hof-controllers/pull/38 fixes this but as discussed I will be moving it to hmpo-form-wizard

**Comment by joefitter** [comment]
Also if we are moving forking then this issue should be closed as no longer belongs here

**Comment by joefitter** [comment]
Thinking about this more, I agree with @daniel-ac-martin's earlier suggestion of getting rid of forks and adding the ability to pass a function as `next` property. Thoughts @easternbloc @JoeChapman?

**Comment by JoeChapman** [comment]
@joefitter At this stage I am open to most suggestions. In many ways a `next` property is perhaps more fitting, whatever you call it, it is in fact the value of the "next" route we are trying to calculate. 
I would like to see some progress on the concept, though, however we tackle it.

**Comment by daniel-ac-martin** [comment]
My worry is that forks cannot really be done properly without serious changes to the architecture.

One solution would be for session variables to be associated with their step. e.g.

``` js
var session = {
  'step-1': {
    'foo': 'bar'
  },
  'step-2a': {
    'baz': 'qux'
  },
  'step-2b': {
    'quux': 'corge'
  }
};
```

That way if we know that the user completed the form using the following steps:
step-1 -> step-2b

Then we know to ignore step-2a and with it the value of 'baz'.

But even this doesn't save us from crazy validation that depends on previous steps. (Maybe 'invalidates' does, I'm not sure.)

Ultimately, the form should be validated in it's entirety rather than just step by step. But it simply hasn't be written that way.

Anyway, perhaps we should close this issue soon and open a more specific one. (The original, associated PR has long since been merged.)

**Comment by joefitter** [comment]
@daniel-ac-martin my previous PR attempts to resolve this - https://github.com/UKHomeOffice/hof-controllers/pull/38 this removes unreachable steps from the session along with any fields, I will move this over to the passports-form-controller though as thats where the forking logic will live

**Comment by joefitter** [comment]
but yes, lets close this issue

**Comment by easternbloc** [comment]
closing this here.
